remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Flight and Critical Care Paramedic Program
description: Comprehensive Course Materials, Resources, and Outline
show_downloads: false

# Customize these as needed
github:
  is_project_page: false

# You can add more custom variables here
