remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Flight and Critical Care Paramedic Program
description: Comprehensive Course Materials and Resources
show_downloads: false

# You can add more custom variables here if needed
